<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>RTSPWallpaperStudio.Renderer</RootNamespace>
    <AssemblyName>RTSPWallpaperStudio.Renderer</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RTSPWallpaperStudio.Core\RTSPWallpaperStudio.Core.csproj" />
    <ProjectReference Include="..\RTSPWallpaperStudio.Interop\RTSPWallpaperStudio.Interop.csproj" />
    <PackageReference Include="LibVLCSharp.WPF" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" />
  </ItemGroup>
</Project>
